# Figure 7A-C: Rice auxin model — linear model performance and residual analysis
# Run with working directory = iSensors-supplementary/
#
# Input:  00-iSensors-objects/data/wang_rice_avg_exp_iSensors_mean.rds
#           AverageExpression matrix (OSA sensors × Organ--CellType groups)
#           Generated by 00-iSensors-objects/wang-rice-iSensors-objects.R
# Output: Manuscript-Figures/out/Figure7A_*.pdf / .svg
#         Manuscript-Figures/out/Figure7B_*.pdf / .svg
#         Manuscript-Figures/out/Figure7C_*.pdf / .svg
#         Manuscript-Figures/out/Figure7_combined.pdf / .svg

library(ggplot2)
library(patchwork)
library(dplyr)
library(tidyr)
library(stringr)

output_dir <- "Manuscript-Figures/out"

# ── Load pre-computed average expression matrix ───────────────────────────────
avg_mat <- readRDS("00-iSensors-objects/data/wang_rice_avg_exp_iSensors_mean.rds")
avg_mat <- as.matrix(avg_mat)
message("Loaded avg_mat: ", nrow(avg_mat), " sensors x ", ncol(avg_mat), " groups")
message("Sensors: ", paste(rownames(avg_mat), collapse = ", "))
message("Sample groups: ", paste(head(colnames(avg_mat), 5), collapse = ", "))

# ── Polish OSA sensor names ───────────────────────────────────────────────────
polish_name <- function(x) {
  x <- gsub("^OSA-aux-trans-|^OSA-aux-cis-|^OSA-aux-cistrans-|^OSA-aux-reg-", "", x)
  x <- gsub("^OS-aux-trans-|^OS-aux-cis-|^OS-aux-cistrans-|^OS-aux-reg-",     "", x)
  gsub("PolarAuxinTransport", "PAT", x)
}
rownames(avg_mat) <- polish_name(rownames(avg_mat))
message("Polished sensors: ", paste(rownames(avg_mat), collapse = ", "))

# ── Build long-format data ────────────────────────────────────────────────────
# Column names are "Organ--CellType"; Seurat replaces "_" with "-" in group names
df_long <- as.data.frame(t(avg_mat), check.names = FALSE) %>%
  tibble::rownames_to_column("group") %>%
  pivot_longer(-group, names_to = "sensor", values_to = "value") %>%
  separate(group, into = c("Organ", "Tissue_Cleaned"),
           sep = "--", extra = "merge", fill = "right")

message("df_long rows: ", nrow(df_long))

# ── Organ rename map and display order ────────────────────────────────────────
organ_rename_map <- c(
  Bud  = "Bud",
  Flag = "Flag leaf",
  leaf = "Leaf",
  Root = "Root",
  SAM  = "Shoot apical meristem",
  Seed = "Seed",
  SP   = "Spikelet",
  ST   = "Stem"
)

organ_order <- c(
  "Root", "Shoot apical meristem", "Bud",
  "Leaf", "Flag leaf", "Stem",
  "Spikelet", "Seed"
)

df_long <- df_long %>%
  mutate(Organ = if_else(Organ %in% names(organ_rename_map),
                         organ_rename_map[Organ], Organ),
         Organ = factor(Organ, levels = organ_order))

# ── Pivot wide for modelling ──────────────────────────────────────────────────
# OSA sensors: ARF, synthesis, IAA (conjugation/deconjugation), PAT
# Rename IAA → Conjugation to match Figure 6 conceptual framework
df_wide <- df_long %>%
  filter(sensor %in% c("ARF", "synthesis", "IAA", "PAT")) %>%
  mutate(sensor = recode(sensor,
                         synthesis = "Synthesis",
                         IAA       = "Conjugation")) %>%
  pivot_wider(id_cols    = c(Organ, Tissue_Cleaned),
              names_from  = sensor,
              values_from = value) %>%
  drop_na(ARF, Synthesis, Conjugation, PAT)

message("Model dataset: ", nrow(df_wide), " tissue-organ combinations")

# ── Linear model: ARF ~ 0 + Synthesis + Conjugation + PAT ────────────────────
m2 <- lm(ARF ~ 0 + Synthesis + Conjugation + PAT, data = df_wide)

df_wide$ARF_hat <- predict(m2)
df_wide$resid   <- resid(m2)
rmse <- sqrt(mean(df_wide$resid^2))

s      <- summary(m2)
r2_adj <- round(s$adj.r.squared, 2)
fstat  <- s$fstatistic
pval   <- pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)
plab   <- if (pval < 2.2e-16) "p < 2.2e-16" else paste0("p = ", signif(pval, 2))
message("Model: adj.R² = ", r2_adj, ", ", plab)

write.csv(df_wide, "Manuscript-Figures/in/Figure7_rice_model_data.csv",
          row.names = FALSE)
message("Exported rice model data")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7A: Scatter — observed vs predicted
# ══════════════════════════════════════════════════════════════════════════════
arf_range <- range(c(df_wide$ARF, df_wide$ARF_hat), na.rm = TRUE)
band_7a <- tibble(x = seq(arf_range[1], arf_range[2], length.out = 200)) %>%
  mutate(lo = x - rmse, hi = x + rmse)

p_7a <- ggplot(df_wide, aes(x = ARF, y = ARF_hat)) +
  geom_ribbon(data = band_7a, aes(x = x, ymin = lo, ymax = hi),
              inherit.aes = FALSE, fill = "grey80", alpha = 0.45) +
  geom_point(size = 2, alpha = 0.8, color = "#4d4d4d") +
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", linewidth = 0.8) +
  coord_equal(xlim = arf_range, ylim = arf_range) +
  annotate("text", x = arf_range[1], y = arf_range[2],
           label = paste0("adj. R² = ", r2_adj, "\n", plab),
           hjust = 0, vjust = 1, size = 3.2, color = "grey30") +
  labs(x = "Observed ARF iSensor", y = "Predicted auxin level") +
  theme_classic(base_size = 11) +
  theme(axis.line  = element_line(linewidth = 0.4),
        axis.ticks = element_line(linewidth = 0.3),
        panel.grid = element_blank())

ggsave(file.path(output_dir, "Figure7A_rice_ARF_scatter.pdf"),
       plot = p_7a, width = 4, height = 4, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "Figure7A_rice_ARF_scatter.svg"),
       plot = p_7a, width = 4, height = 4, dpi = 300, bg = "white")
message("Saved Figure 7A")


# ══════════════════════════════════════════════════════════════════════════════
# Shared forest-plot helper
# ══════════════════════════════════════════════════════════════════════════════
rse <- s$sigma

make_forest <- function(summary_df, x_col, title_lab) {
  df <- summary_df %>%
    arrange(mean_resid) %>%
    mutate(!!x_col := factor(.data[[x_col]], levels = .data[[x_col]]))

  ggplot(df, aes(x = .data[[x_col]], y = mean_resid)) +
    geom_rect(ymin = -rse,       ymax =  rse,
              xmin = -Inf, xmax = Inf,
              fill = "grey90", alpha = 0.6, inherit.aes = FALSE) +
    geom_rect(ymin = -0.3 * rse, ymax =  0.3 * rse,
              xmin = -Inf, xmax = Inf,
              fill = "grey75", alpha = 0.8, inherit.aes = FALSE) +
    geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.5,
               colour = "grey40") +
    geom_errorbar(aes(ymin = mean_resid - se_resid,
                      ymax = mean_resid + se_resid),
                  width = 0.25, linewidth = 0.5) +
    geom_point(size = 2.5) +
    coord_flip() +
    labs(x = NULL,
         y = "Mean residual (observed − predicted)",
         title = title_lab) +
    theme_classic(base_size = 10) +
    theme(plot.title  = element_text(face = "bold", size = 10),
          axis.line   = element_line(linewidth = 0.4),
          axis.ticks  = element_line(linewidth = 0.3),
          axis.text.y = element_text(size = 8),
          panel.grid  = element_blank())
}


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7B: Organ-level residuals
# ══════════════════════════════════════════════════════════════════════════════
organ_summary <- df_wide %>%
  group_by(Organ) %>%
  summarise(mean_resid = mean(resid),
            se_resid   = sd(resid) / sqrt(n()),
            n          = n(), .groups = "drop")

p_7b <- make_forest(organ_summary, "Organ", "Organ level")

ggsave(file.path(output_dir, "Figure7B_rice_organ_residuals.pdf"),
       plot = p_7b, width = 4, height = 4, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "Figure7B_rice_organ_residuals.svg"),
       plot = p_7b, width = 4, height = 4, dpi = 300, bg = "white")
message("Saved Figure 7B")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7C: Tissue-level residuals (broad categories)
# Note: Seurat replaces "_" with "-" in group names, so cell types use dashes
# ══════════════════════════════════════════════════════════════════════════════
df_wide <- df_wide %>%
  mutate(Tissue_Broad = case_when(
    str_detect(Tissue_Cleaned, regex("epidermis|guard.cell|atrichoblast|trichoblast",   ignore_case = TRUE)) ~ "Epidermis",
    str_detect(Tissue_Cleaned, regex("vascular|procambium|xylem|phloem|stele",         ignore_case = TRUE)) ~ "Vascular",
    str_detect(Tissue_Cleaned, regex("parenchyma|collenchymat",                        ignore_case = TRUE)) ~ "Parenchyma",
    str_detect(Tissue_Cleaned, regex("mesophyll",                                      ignore_case = TRUE)) ~ "Mesophyll",
    str_detect(Tissue_Cleaned, regex("cortex",                                         ignore_case = TRUE)) ~ "Cortex",
    str_detect(Tissue_Cleaned, regex("endodermis|exodermis",                           ignore_case = TRUE)) ~ "Endodermal",
    str_detect(Tissue_Cleaned, regex("columella|root.cap|lrc",                         ignore_case = TRUE)) ~ "Root cap / LRC",
    str_detect(Tissue_Cleaned, regex("meristem|initials|proliferating|primordium|apical|axis", ignore_case = TRUE)) ~ "Meristematic",
    str_detect(Tissue_Cleaned, regex("fiber|sclerenchyma",                             ignore_case = TRUE)) ~ "Fibers",
    str_detect(Tissue_Cleaned, regex("tapetum|pollen|ovule|ovary|stigmata|filament|lodicule|scutellum|plumule|mother.cell", ignore_case = TRUE)) ~ "Reproductive",
    str_detect(Tissue_Cleaned, regex("unknown",                                        ignore_case = TRUE)) ~ "Unknown",
    TRUE ~ Tissue_Cleaned
  ))

tissue_summary <- df_wide %>%
  group_by(Tissue_Broad) %>%
  summarise(mean_resid = mean(resid, na.rm = TRUE),
            se_resid   = sd(resid, na.rm = TRUE) / sqrt(n()),
            n          = n(), .groups = "drop") %>%
  filter(n >= 2)

p_7c <- make_forest(tissue_summary, "Tissue_Broad", "Tissue level")

ggsave(file.path(output_dir, "Figure7C_rice_tissue_residuals.pdf"),
       plot = p_7c, width = 4, height = 5, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "Figure7C_rice_tissue_residuals.svg"),
       plot = p_7c, width = 4, height = 5, dpi = 300, bg = "white")
message("Saved Figure 7C")


# ══════════════════════════════════════════════════════════════════════════════
# Figure 7 combined: A (scatter) | B (organ forest) | C (tissue forest)
# ══════════════════════════════════════════════════════════════════════════════
fig7_combined <- (p_7a | p_7b | p_7c) +
  plot_layout(widths = c(1, 1, 1.5)) +
  plot_annotation(
    tag_levels = "A",
    theme = theme(plot.tag = element_text(face = "bold", size = 13))
  ) & theme(plot.margin = margin(4, 8, 4, 8, "pt"))

ggsave(file.path(output_dir, "Figure7_combined.pdf"),
       plot = fig7_combined,
       width = 12, height = 5, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "Figure7_combined.svg"),
       plot = fig7_combined,
       width = 12, height = 5, dpi = 300, bg = "white")
message("Saved Figure 7 combined: Figure7_combined.pdf / .svg")
