#!/usr/bin/env Rscript

# Mirrored ARF-only root comparison.
# Uses the source data generated by Figure7_root_species_tissue_average.R.
#
# Run from iSensors-supplementary/:
# Rscript Manuscript-Figures/Figure7_root_ARF_mirrored.R

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(RColorBrewer)
})

input_csv <- paste0(
  "Manuscript-Figures/in/",
  "Figure7D_root_Arabidopsis_vs_rice_tissue_mean_iSensors.csv"
)
output_stem <- paste0(
  "Manuscript-Figures/out/",
  "Figure7D_root_Arabidopsis_vs_rice_ARF_mirrored"
)

tissue_order <- c(
  "Stem cell niche",
  "Epidermis",
  "Cortex",
  "Endodermis",
  "Pericycle",
  "Xylem",
  "Root cap"
)

# Match the Brewer-derived palette construction used for Figure 6A.
tissue_colors <- setNames(
  colorRampPalette(c(
    brewer.pal(12, "Paired"),
    brewer.pal(8, "Set2"),
    brewer.pal(8, "Dark2")
  ))(length(tissue_order)),
  tissue_order
)

plot_data <- read.csv(input_csv, check.names = FALSE)

arf_mirror <- plot_data %>%
  filter(sensor == "ARF") %>%
  mutate(
    tissue = recode(tissue, `Pericycle (XPP)` = "Pericycle")
  ) %>%
  filter(tissue %in% tissue_order) %>%
  mutate(
    tissue = factor(tissue, levels = tissue_order),
    direction = if_else(
      species == "Arabidopsis\n(Shahan)",
      1,
      -1
    ),
    mirrored_mean = direction * relative_mean,
    mirrored_se_low = if_else(
      direction > 0,
      pmax(relative_mean - relative_se, 0),
      -(relative_mean + relative_se)
    ),
    mirrored_se_high = if_else(
      direction > 0,
      relative_mean + relative_se,
      -pmax(relative_mean - relative_se, 0)
    )
  )

p <- ggplot(
  arf_mirror,
  aes(x = tissue, y = mirrored_mean, fill = tissue)
) +
  geom_hline(yintercept = 0, linewidth = 0.45, color = "grey20") +
  geom_col(width = 0.72, color = "grey25", linewidth = 0.25) +
  geom_errorbar(
    aes(ymin = mirrored_se_low, ymax = mirrored_se_high),
    width = 0.17,
    linewidth = 0.35
  ) +
  annotate(
    "text",
    x = 0.55,
    y = 1.04,
    label = "Arabidopsis (Shahan)",
    hjust = 0,
    vjust = 1,
    fontface = "bold",
    size = 4
  ) +
  annotate(
    "text",
    x = 0.55,
    y = -1.04,
    label = "Rice (Wang)",
    hjust = 0,
    vjust = 0,
    fontface = "bold",
    size = 4
  ) +
  scale_fill_manual(values = tissue_colors, guide = "none", drop = FALSE) +
  scale_y_continuous(
    limits = c(-1.08, 1.08),
    breaks = c(-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1),
    labels = function(x) abs(x),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    x = NULL,
    y = "Relative mean ARF iSensor signal"
  ) +
  theme_classic(base_size = 11) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 9),
    axis.title.y = element_text(size = 10),
    axis.line.x = element_blank(),
    axis.line.y = element_line(linewidth = 0.4),
    axis.ticks = element_line(linewidth = 0.3),
    panel.grid = element_blank(),
    plot.margin = margin(8, 10, 8, 10)
  )

ggsave(paste0(output_stem, ".pdf"), p, width = 9, height = 6.5)
ggsave(paste0(output_stem, ".svg"), p, width = 9, height = 6.5)
ggsave(
  paste0(output_stem, ".png"),
  p,
  width = 9,
  height = 6.5,
  dpi = 350,
  bg = "white"
)

message("Saved mirrored ARF plot: ", output_stem, ".pdf")
